// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR6EtbTM_YKUD66AtwxQ47ovnKMBDUs9k',
    appId: '1:957750528101:web:8190b05773b68b9f6bde8c',
    messagingSenderId: '957750528101',
    projectId: 'velo-app-dd510',
    authDomain: 'velo-app-dd510.firebaseapp.com',
    storageBucket: 'velo-app-dd510.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK8BZADYqoLE6TH9FLXeCRHxNqk47kMaM',
    appId: '1:957750528101:android:9a715cee217d5c3d6bde8c',
    messagingSenderId: '957750528101',
    projectId: 'velo-app-dd510',
    storageBucket: 'velo-app-dd510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPPnWqlqZJ8hSpN6SDZSzpmuLcEA1YbI',
    appId: '1:957750528101:ios:708a462fe2f1c5c36bde8c',
    messagingSenderId: '957750528101',
    projectId: 'velo-app-dd510',
    storageBucket: 'velo-app-dd510.firebasestorage.app',
    iosBundleId: 'com.example.karaba',
  );
}
